import { supabase } from './supabaseClient';

export interface AudioAsset {
    name: string;
    path: string; // This will be the public URL
}

/**
 * Uploads an audio file to Supabase Storage and saves its metadata to the database.
 * @param file The audio file to upload.
 * @param type The type of audio ('bgm' or 'sfx').
 * @param isAiGenerated Whether the file was generated by AI.
 * @param prompt The prompt used for AI generation, if applicable.
 * @returns The public URL of the uploaded file.
 */
export const uploadAudioFile = async (
    file: File,
    type: 'bgm' | 'sfx',
    isAiGenerated: boolean = false,
    prompt: string | null = null
): Promise<string> => {
    
    const fileName = `${Date.now()}-${file.name.replace(/\s+/g, '_')}`;
    const filePath = `${type}/${fileName}`;

    // 1. Upload the file to Supabase Storage
    const { data: uploadData, error: uploadError } = await supabase.storage
        .from('public') // Changed bucket to 'public'
        .upload(filePath, file);

    if (uploadError) {
        console.error('Supabase upload error:', uploadError);
        throw new Error(`Failed to upload audio to storage: ${uploadError.message}`);
    }

    // 2. Get the public URL of the uploaded file
    const { data: urlData } = supabase.storage
        .from('public') // Changed bucket to 'public'
        .getPublicUrl(filePath);
        
    const publicUrl = urlData.publicUrl;

    // 3. Insert metadata into the database
    const { error: dbError } = await supabase
        .from('audio_files')
        .insert({
            file_name: file.name,
            file_path: filePath,
            public_url: publicUrl,
            audio_type: type,
            generated_by_ai: isAiGenerated,
            prompt: prompt
        });

    if (dbError) {
        // Attempt to delete the orphaned file from storage if DB insert fails
        await supabase.storage.from('public').remove([filePath]);
        console.error('Supabase DB insert error:', dbError);
        throw new Error(`Failed to save audio metadata: ${dbError.message}`);
    }

    return publicUrl;
};

/**
 * Lists all available audio files of a specific type from the database.
 * @param type The type of audio to fetch ('bgm' or 'sfx').
 * @returns A promise that resolves to an array of audio assets.
 */
export const listAudioFiles = async (type: 'bgm' | 'sfx'): Promise<AudioAsset[]> => {
    const { data, error } = await supabase
        .from('audio_files')
        .select('file_name, public_url')
        .eq('audio_type', type)
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Supabase list error:', error);
        throw new Error(`Failed to fetch audio files: ${error.message}`);
    }

    return data.map(item => ({
        name: item.file_name || 'Untitled Audio',
        path: item.public_url
    }));
};

/**
 * Uploads a video file to Supabase Storage and saves its metadata to the database.
 * @param file The video file to upload.
 * @param fileName The desired file name for the uploaded video.
 * @param isAiGenerated Whether the file was generated by AI.
 * @param prompt The prompt used for AI generation, if applicable.
 * @returns The public URL of the uploaded file.
 */
export const uploadVideoFile = async (
    file: Blob,
    fileName: string,
    isAiGenerated: boolean = true, // Videos generated by this app are AI-generated
    prompt: string | null = null
): Promise<string> => {
    
    const uniqueFileName = `${Date.now()}-${fileName.replace(/\s+/g, '_')}`;
    const filePath = `videos/${uniqueFileName}`;

    // 1. Upload the file to Supabase Storage
    const { data: uploadData, error: uploadError } = await supabase.storage
        .from('public')
        .upload(filePath, file, {
            contentType: 'video/mp4', // Assuming MP4 for now
        });

    if (uploadError) {
        console.error('Supabase video upload error:', uploadError);
        throw new Error(`Failed to upload video to storage: ${uploadError.message}`);
    }

    // 2. Get the public URL of the uploaded file
    const { data: urlData } = supabase.storage
        .from('public')
        .getPublicUrl(filePath);
        
    const publicUrl = urlData.publicUrl;

    // 3. Insert metadata into the database
    const { error: dbError } = await supabase
        .from('video_files') // Assuming a 'video_files' table exists
        .insert({
            file_name: fileName,
            file_path: filePath,
            public_url: publicUrl,
            generated_by_ai: isAiGenerated,
            prompt: prompt
        });

    if (dbError) {
        // Attempt to delete the orphaned file from storage if DB insert fails
        await supabase.storage.from('public').remove([filePath]);
        console.error('Supabase video DB insert error:', dbError);
        throw new Error(`Failed to save video metadata: ${dbError.message}`);
    }

    return publicUrl;
};
